### PR TITLE
Convert variables, messages to english

### PR DESCRIPTION
**Pull request by DilanAnuruddha**
@DilanAnuruddha
Convert variables, messages to english

### CODE REVIEW

**Comment by romavini** [comment]
Thanks for your contribution! I will review the code soon! ^^

**Comment by romavini** [comment]
I merged a PR that removes comments and that conflict with your PR. Do you mind fixing the conflict?

**Comment by DilanAnuruddha** [comment]
yes sure.Please assign to me

**Comment by romavini** [comment]
Hi! As you opened PR #15 for the same issue #3 I will decline here at #10.

**Pull request closed without merging**
